#!/usr/bin/env python3
"""Build the app's sender-header -> brand map from data/brands.json and the DLT registry.

A header maps to a brand only when its registered principal entity is exactly one of the brand's
owners. Headers stay case-sensitive. Fails if an owner string is not in the registry (typo or the
company was renamed) or a brand has no logo.

Usage: scripts/dlt/build_brand_map.py
"""
import csv, json, os, sys
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
REGISTRY = os.path.join(ROOT, 'data/dlt/jio-headers.csv')
BRANDS = os.path.join(ROOT, 'data/brands.json')
LOGOS = os.path.join(ROOT, 'app/src/main/res/drawable-nodpi')
OUT = os.path.join(ROOT, 'app/src/main/assets/sender_brands.tsv')


def main():
    brands = json.load(open(BRANDS, encoding='utf-8'))['brands']
    owner_to_brand, errors = {}, []
    for b in brands:
        for owner in b['owners']:
            if owner in owner_to_brand:
                errors.append(f"{owner!r} is claimed by {owner_to_brand[owner]} and {b['id']}")
            owner_to_brand[owner] = b['id']

    rows = list(csv.DictReader(open(REGISTRY, encoding='utf-8')))
    known_owners = {r['principal_entity'] for r in rows}
    errors += [f"owner not in registry: {o!r}" for o in owner_to_brand if o not in known_owners]
    if errors:
        sys.exit("\n".join(errors))

    # Brands without an approved logo keep their curated owners but are left out of the app map.
    with_logo = {b['id'] for b in brands if os.path.exists(os.path.join(LOGOS, f"brand_{b['id']}.webp"))}
    pending = sorted({b['id'] for b in brands} - with_logo)
    mapping = sorted((r['header'], owner_to_brand[r['principal_entity']])
                     for r in rows if owner_to_brand.get(r['principal_entity']) in with_logo)
    # Networks sometimes deliver a header in a different case than registered ("Airtel" for AIRTEL).
    # Allow a case-insensitive match ("~UPPER" keys) only when every case variant of that header in
    # the whole registry belongs to the same company, so INDIGO/IndiGo (airline) vs Indigo (paints)
    # never fall back.
    owners_by_upper = {}
    for r in rows:
        owners_by_upper.setdefault(r['header'].upper(), set()).add(r['principal_entity'])
    fallback = sorted({(f"~{h.upper()}", b) for h, b in mapping if len(owners_by_upper[h.upper()]) == 1})
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write("# Generated by scripts/dlt/build_brand_map.py from data/brands.json. Do not edit.\n")
        f.writelines(f"{h}\t{b}\n" for h, b in mapping + fallback)
    per_brand = Counter(b for _, b in mapping)
    print(f"{len(mapping)} headers (+{len(fallback)} case-insensitive) -> {len(per_brand)} brands -> {os.path.relpath(OUT, ROOT)}")
    if pending:
        print(f"no logo yet (not in app map): {', '.join(pending)}")
    unused = [b for b in with_logo if b not in per_brand]
    if unused:
        sys.exit(f"brands with no headers: {unused}")


if __name__ == '__main__':
    main()
